"""empty message

Revision ID: 0cccbd78c1f3
Revises: c55c2ebd3c5d
Create Date: 2018-04-23 21:27:12.345325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cccbd78c1f3'
down_revision = 'c55c2ebd3c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'tags')
    # ### end Alembic commands ###
